version: "3.7"

services:
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    expose:
      - "3000"
    environment:
      NODE_ENV: development
      PORT: 3000

  client:
    image: nginx:alpine
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    expose:
      - "8080"

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "80:80"
    # links:
    #   - server
    #   - client
